name: lambdabot-haskell-plugins
version: '5.1'
synopsis: Lambdabot Haskell plugins
description: ! 'Lambdabot is an IRC bot written over several years by

  those on the #haskell IRC channel.


  Provided plugins:


  [check] Quick, check!


  [djinn] Derive implementations from types intuitinistically.


  [eval] Run Haskell code.


  [free] Theorems for free.


  [haddock] Find modules implementing a function.


  [hoogle] Search for functions by type using hoogle.


  [instances] Query instances of type classes.


  [pl] Produce point-less code.


  [pointful] Produce point-ful code.


  [pretty] Print code prettily.


  [source] Show implementations of standard functions.


  [type] Query type of expressions.


  [undo] Unfold do notation.


  [unmtl] Expand monad transformers stacks.'
category: Development, Web
author: Don Stewart
maintainer: James Cook <mokus@deepbondi.net>
license: GPL
github: lambdabot/lambdabot.git
homepage: http://haskell.org/haskellwiki/Lambdabot
tested-with: GHC==7.8.4 GHC==7.10.3
extra-source-files:
- src/Lambdabot/Plugin/Haskell/Free/Test.hs
ghc-options:
- -Wall
- -funbox-strict-fields
dependencies:
- array >=0.4
- base >=4.4 && <5
- bytestring >=0.9
- containers >=0.4
- directory >=1.1
- filepath >=1.3
- haskell-src-exts >=1.17.0 && <1.18
- lambdabot-core >=5.1 && <5.2
- lambdabot-reference-plugins >=5.1 && <5.2
- lifted-base >=0.2
- mtl >=2
- oeis >=0.3.1
- parsec >=3
- pretty >=1.1
- process >=1.1
- QuickCheck >=2
- regex-tdfa >=1.1
- split >=0.2
- syb >=0.3
- transformers >=0.2
- utf8-string >=0.3
- arrows >=0.4
- data-memocombinators >=0.4
- hoogle >=4.2
- IOSpec >=0.2
- lambdabot-trusted >=5.1 && <5.2
- logict >=0.5
- MonadRandom >=0.1
- mueval >=0.9.1.1.2
- numbers >=3000
- show >=0.4
- vector-space >=0.8
- HTTP >=4000
- network >=2.3.0.13
library:
  source-dirs: src
  exposed-modules:
  - Lambdabot.Plugin.Haskell
