name: mueval
version: '0.9.3'
synopsis: Safely evaluate pure Haskell expressions
description: ! 'Mueval is a Haskell interpreter. It

  uses the GHC API to evaluate arbitrary Haskell expressions.

  Importantly, mueval takes many precautions to defang and avoid \"evil\"

  code.  It uses resource limits, whitelisted modules and Safe Haskell,

  special Show instances for IO, threads, processes, and changes of directory

  to sandbox the Haskell code.


  It is, in short, intended to be a standalone version of Lambdabot''s famous

  evaluation functionality. For examples and explanations, please see the README file.


  Mueval is POSIX-only.'
category: Development, Language
author: Gwern
maintainer: Gwern <gwern@gwern.net>
license: BSD3
homepage: https://github.com/gwern/mueval
git: git://github.com/gwern/mueval.git
tested-with: GHC==6.10.1
extra-source-files:
- build.sh
- tests.sh
ghc-options:
- -Wall
- -static
dependencies:
- base >=4.5 && <5
- containers
- directory
- mtl >2
- filepath
- unix
- process
- hint >=0.3.1
- show >=0.3
- Cabal
- extensible-exceptions
- simple-reflect
- QuickCheck
- lens
library:
  exposed-modules:
  - Mueval.Parallel
  - Mueval.Context
  - Mueval.Interpreter
  - Mueval.ArgsParse
  - Mueval.Resources
executables:
  mueval-core:
    main: main.hs
    ghc-options:
    - -threaded
    dependencies:
    - base
    other-modules:
        Mueval.ArgsParse
        Mueval.Context
        Mueval.Interpreter
        Mueval.Parallel
        Mueval.Resources
  mueval:
    main: watchdog.hs
    ghc-options:
    - -threaded
    dependencies:
    - base
data-files:
- HCAR.tex
- README.md
